overrides:
  zod: ">=3.25"

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
shamefully-hoist: true
