import "dotenv/config";
import prisma from "@/lib/prisma";
import {
  TipoSolicitud,
  TipoCuenta,
  TipoPersonal,
} from "@/generated/prisma/enums";

async function main() {
  await prisma.accountRequest.deleteMany();

  const data = [
    // 1. Juan Pérez - ALTA, PERMANENTE, TECNICO - Acceso completo
    {
      folio: "FOL-2026-001",
      tipoSolicitud: TipoSolicitud.ALTA,
      tipoCuenta: TipoCuenta.PERMANENTE,
      nombreApellidos: "Juan Pérez",
      telefonoExtension: "Ext. 101",
      cargoOcupa: "Analista",
      departamentoArea: "TI",
      tipoPersonal: TipoPersonal.TECNICO,
      identificadorCuentaUsuario: "jperez",
      correoNacional: true,
      correoInternacional: true,
      correoInternet: true,
      intranetUNE: true,
      intranetNacional: true,
      internet: true,
      mensajeriaCorporativa: true,
      facebook: true,
      twitter: true,
      youtube: true,
      whatsapp: true,
      telegram: true,
      adminRed: true,
      adminLocal: true,
      usuarioAvanzado: true,
      accesoNubeLectura: true,
      accesoNubeModificar: true,
      accesoNubeBorrar: true,
      accesoNubeControlTotal: true,
      horarioExtralaboral: true,
      extraDesde: "18:00",
      extraHasta: "22:00",
      sabadoDesde: "08:00",
      sabadoHasta: "14:00",
      apnCorreoNacional: true,
      apnInternet: true,
      telefonoCelular: "555-123-4567",
      pcNombre: "PC-JPEREZ-001",
      pcInventario: "INV-001",
      softwareAutorizado: "Visual Studio Code, Docker, PostgreSQL, Node.js",
      cuentaUsuario: "jperez@empresa.com",
      actividadRealiza: "Desarrollo y mantenimiento de sistemas internos",
      administradorSistema: true,
      solicitadoFecha: new Date("2026-06-01"),
      revisadoFecha: new Date("2026-06-03"),
      aprobadoFecha: new Date("2026-06-05"),
      ejecutadoFecha: new Date("2026-06-06"),
    },
    // 2. María López - ALTA, PERMANENTE, DIRECTIVO - Solo correo e intranet básicos
    {
      folio: "FOL-2026-002",
      tipoSolicitud: TipoSolicitud.ALTA,
      tipoCuenta: TipoCuenta.PERMANENTE,
      nombreApellidos: "María López",
      cargoOcupa: "Directora",
      departamentoArea: "RRHH",
      tipoPersonal: TipoPersonal.DIRECTIVO,
      identificadorCuentaUsuario: "mlopez",
      correoNacional: true,
      intranetUNE: true,
      intranetNacional: true,
      internet: true,
      mensajeriaCorporativa: true,
      pcNombre: "PC-MLOPEZ-001",
      pcInventario: "INV-002",
      softwareAutorizado: "Office 365, Nómina SQL",
      cuentaUsuario: "mlopez@empresa.com",
      actividadRealiza: "Dirección de recursos humanos",
      telefonoCelular: "555-111-2222",
      solicitadoFecha: new Date("2026-06-02"),
      revisadoFecha: new Date("2026-06-04"),
      aprobadoFecha: new Date("2026-06-06"),
      ejecutadoFecha: new Date("2026-06-07"),
    },
    // 3. Roberto Sánchez - ALTA, PERMANENTE, OTRO
    {
      folio: "FOL-2026-003",
      tipoSolicitud: TipoSolicitud.ALTA,
      tipoCuenta: TipoCuenta.PERMANENTE,
      nombreApellidos: "Roberto Sánchez",
      cargoOcupa: "Coordinador",
      departamentoArea: "Operaciones",
      tipoPersonal: TipoPersonal.OTRO,
      identificadorCuentaUsuario: "rsanchez",
      correoNacional: true,
      intranetUNE: true,
      internet: true,
      mensajeriaCorporativa: true,
      pcNombre: "PC-RSANCHEZ-001",
      pcInventario: "INV-003",
      softwareAutorizado: "Office 365, SAP",
      cuentaUsuario: "rsanchez@empresa.com",
      actividadRealiza: "Coordinación de operaciones",
      telefonoCelular: "555-222-3333",
      solicitadoFecha: new Date("2026-06-03"),
      revisadoFecha: new Date("2026-06-05"),
      aprobadoFecha: new Date("2026-06-07"),
      ejecutadoFecha: new Date("2026-06-08"),
    },
    // 4. Laura García - ALTA, TEMPORAL, ESPECIALISTA_PRINCIPAL - Con expiración
    {
      folio: "FOL-2026-004",
      tipoSolicitud: TipoSolicitud.ALTA,
      tipoCuenta: TipoCuenta.TEMPORAL,
      nombreApellidos: "Laura García",
      cargoOcupa: "Especialista",
      departamentoArea: "Sistemas",
      tipoPersonal: TipoPersonal.ESPECIALISTA_PRINCIPAL,
      identificadorCuentaUsuario: "lgarcia",
      correoNacional: true,
      correoInternacional: true,
      correoInternet: true,
      intranetUNE: true,
      intranetNacional: true,
      internet: true,
      mensajeriaCorporativa: true,
      usuarioAvanzado: true,
      accesoNubeLectura: true,
      accesoNubeModificar: true,
      fechaExpiracion: new Date("2026-12-31"),
      pcNombre: "PC-LGARCIA-001",
      pcInventario: "INV-004",
      softwareAutorizado: "VMware, Ansible, Terraform",
      cuentaUsuario: "lgarcia@empresa.com",
      actividadRealiza: "Administración de infraestructura",
      administradorSistema: true,
      telefonoCelular: "555-333-4444",
      solicitadoFecha: new Date("2026-06-05"),
      revisadoFecha: new Date("2026-06-07"),
      aprobadoFecha: new Date("2026-06-09"),
      ejecutadoFecha: new Date("2026-06-10"),
    },
    // 5. Diego Fernández - ALTA, TEMPORAL, TECNICO - Horario extralaboral
    {
      folio: "FOL-2026-005",
      tipoSolicitud: TipoSolicitud.ALTA,
      tipoCuenta: TipoCuenta.TEMPORAL,
      nombreApellidos: "Diego Fernández",
      cargoOcupa: "Técnico",
      departamentoArea: "Redes",
      tipoPersonal: TipoPersonal.TECNICO,
      identificadorCuentaUsuario: "dfernandez",
      correoNacional: true,
      intranetUNE: true,
      internet: true,
      mensajeriaCorporativa: true,
      accesoNubeLectura: true,
      fechaExpiracion: new Date("2026-09-30"),
      horarioExtralaboral: true,
      extraDesde: "20:00",
      extraHasta: "00:00",
      domingoDesde: "10:00",
      domingoHasta: "14:00",
      apnCorreoNacional: true,
      apnInternet: true,
      telefonoCelular: "555-987-6543",
      pcNombre: "PC-DFERNANDEZ-001",
      pcInventario: "INV-005",
      softwareAutorizado: "Wireshark, Putty, Cisco CLI",
      cuentaUsuario: "dfernandez@empresa.com",
      actividadRealiza: "Soporte de redes y conectividad",
      solicitadoFecha: new Date("2026-06-06"),
      revisadoFecha: new Date("2026-06-08"),
      aprobadoFecha: new Date("2026-06-10"),
      ejecutadoFecha: new Date("2026-06-11"),
    },
    // 6. Ana Martínez - ACTUALIZACION, PERMANENTE, DIRECTIVO - Se le agregan permisos
    {
      folio: "FOL-2026-006",
      tipoSolicitud: TipoSolicitud.ACTUALIZACION,
      tipoCuenta: TipoCuenta.PERMANENTE,
      nombreApellidos: "Ana Martínez",
      cargoOcupa: "Jefa",
      departamentoArea: "Finanzas",
      tipoPersonal: TipoPersonal.DIRECTIVO,
      identificadorCuentaUsuario: "amartinez",
      correoNacional: true,
      correoInternacional: true,
      intranetUNE: true,
      intranetNacional: true,
      internet: true,
      mensajeriaCorporativa: true,
      pcNombre: "PC-AMARTINEZ-001",
      pcInventario: "INV-006",
      pcAdicionalNombre: "PC-AMARTINEZ-MOVIL",
      pcAdicionalInventario: "INV-006B",
      softwareAutorizado: "Office 365, SAP FI, Power BI",
      cuentaUsuario: "amartinez@empresa.com",
      actividadRealiza: "Supervisión de finanzas y reportes directivos",
      telefonoCelular: "555-444-5555",
      solicitadoFecha: new Date("2026-06-08"),
      revisadoFecha: new Date("2026-06-10"),
      aprobadoFecha: new Date("2026-06-12"),
      ejecutadoFecha: new Date("2026-06-13"),
    },
    // 7. Carlos Ruiz - ACTUALIZACION, TEMPORAL, TECNICO - Cambio de área
    {
      folio: "FOL-2026-007",
      tipoSolicitud: TipoSolicitud.ACTUALIZACION,
      tipoCuenta: TipoCuenta.TEMPORAL,
      nombreApellidos: "Carlos Ruiz",
      cargoOcupa: "Analista",
      departamentoArea: "TI",
      tipoPersonal: TipoPersonal.TECNICO,
      identificadorCuentaUsuario: "cruiz",
      correoNacional: true,
      correoInternacional: true,
      intranetUNE: true,
      internet: true,
      mensajeriaCorporativa: true,
      usuarioAvanzado: true,
      accesoNubeLectura: true,
      accesoNubeModificar: true,
      fechaExpiracion: new Date("2026-08-15"),
      pcNombre: "PC-CRUIZ-001",
      pcInventario: "INV-007",
      softwareAutorizado: "Postman, Git, VS Code, DBeaver",
      cuentaUsuario: "cruiz@empresa.com",
      actividadRealiza: "Desarrollo backend",
      solicitadoFecha: new Date("2026-06-10"),
      revisadoFecha: new Date("2026-06-12"),
      aprobadoFecha: new Date("2026-06-14"),
      ejecutadoFecha: new Date("2026-06-15"),
    },
    // 8. Sofía Torres - ACTUALIZACION, PERMANENTE, ESPECIALISTA_PRINCIPAL
    {
      folio: "FOL-2026-008",
      tipoSolicitud: TipoSolicitud.ACTUALIZACION,
      tipoCuenta: TipoCuenta.PERMANENTE,
      nombreApellidos: "Sofía Torres",
      cargoOcupa: "Especialista",
      departamentoArea: "Legal",
      tipoPersonal: TipoPersonal.ESPECIALISTA_PRINCIPAL,
      identificadorCuentaUsuario: "storres",
      correoNacional: true,
      correoInternacional: true,
      intranetUNE: true,
      intranetNacional: true,
      internet: true,
      mensajeriaCorporativa: true,
      youtube: true,
      pcNombre: "PC-STORRES-001",
      pcInventario: "INV-008",
      softwareAutorizado: "Office 365, LexisNexis, Dropbox",
      cuentaUsuario: "storres@empresa.com",
      actividadRealiza: "Asesoría legal corporativa",
      telefonoCelular: "555-555-6666",
      solicitadoFecha: new Date("2026-06-12"),
      revisadoFecha: new Date("2026-06-14"),
      aprobadoFecha: new Date("2026-06-16"),
      ejecutadoFecha: new Date("2026-06-17"),
    },
    // 9. Pedro Ramírez - ACTUALIZACION, TEMPORAL, TECNICO - Cambio de horario
    {
      folio: "FOL-2026-009",
      tipoSolicitud: TipoSolicitud.ACTUALIZACION,
      tipoCuenta: TipoCuenta.TEMPORAL,
      nombreApellidos: "Pedro Ramírez",
      cargoOcupa: "Técnico",
      departamentoArea: "Mantenimiento",
      tipoPersonal: TipoPersonal.TECNICO,
      identificadorCuentaUsuario: "pramirez",
      correoNacional: true,
      intranetUNE: true,
      mensajeriaCorporativa: true,
      fechaExpiracion: new Date("2026-07-01"),
      horarioExtralaboral: true,
      extraDesde: "18:00",
      extraHasta: "22:00",
      sabadoDesde: "06:00",
      sabadoHasta: "14:00",
      domingoDesde: "06:00",
      domingoHasta: "12:00",
      pcNombre: "PC-PRAMIREZ-001",
      pcInventario: "INV-009",
      softwareAutorizado: "Autocad, SolidWorks",
      cuentaUsuario: "pramirez@empresa.com",
      actividadRealiza: "Mantenimiento de planta",
      telefonoCelular: "555-666-7777",
      solicitadoFecha: new Date("2026-06-14"),
      revisadoFecha: new Date("2026-06-16"),
      aprobadoFecha: new Date("2026-06-18"),
      ejecutadoFecha: new Date("2026-06-19"),
    },
    // 10. Elena Díaz - Baja
    {
      folio: "FOL-2026-010",
      tipoSolicitud: TipoSolicitud.ALTA,
      tipoCuenta: TipoCuenta.PERMANENTE,
      nombreApellidos: "Elena Díaz",
      cargoOcupa: "Directora",
      departamentoArea: "Comercial",
      tipoPersonal: TipoPersonal.DIRECTIVO,
      identificadorCuentaUsuario: "ediaz",
      correoNacional: true,
      correoInternacional: true,
      intranetUNE: true,
      intranetNacional: true,
      internet: true,
      mensajeriaCorporativa: true,
      pcNombre: "PC-EDIAZ-001",
      pcInventario: "INV-010",
      softwareAutorizado: "Office 365, Salesforce, Tableau",
      cuentaUsuario: "ediaz@empresa.com",
      actividadRealiza: "Dirección comercial",
      telefonoCelular: "555-777-8888",
      motivosBaja: "Cambio a otra institución",
      fechaBaja: new Date("2026-06-20"),
      solicitadoFecha: new Date("2026-01-10"),
      revisadoFecha: new Date("2026-01-12"),
      aprobadoFecha: new Date("2026-01-14"),
      ejecutadoFecha: new Date("2026-01-15"),
    },
    // 11. Pendiente Juan - ALTA, TEMPORAL - Solo solicitado
    {
      folio: "FOL-2026-011",
      tipoSolicitud: TipoSolicitud.ALTA,
      tipoCuenta: TipoCuenta.TEMPORAL,
      nombreApellidos: "Pendiente Juan",
      cargoOcupa: "Analista",
      departamentoArea: "TI",
      tipoPersonal: TipoPersonal.TECNICO,
      identificadorCuentaUsuario: "pendientejuan",
      correoNacional: true,
      intranetUNE: true,
      internet: true,
      mensajeriaCorporativa: true,
      fechaExpiracion: new Date("2026-11-30"),
      pcNombre: "PC-PJUAN-001",
      pcInventario: "INV-011",
      softwareAutorizado: "VS Code, Node.js, MySQL",
      cuentaUsuario: "pendientejuan@empresa.com",
      actividadRealiza: "Análisis de sistemas",
      telefonoCelular: "555-888-9999",
      solicitadoFecha: new Date("2026-06-22"),
    },
    // 12. Pendiente María - ACTUALIZACION, PERMANENTE - Solicitado y revisado
    {
      folio: "FOL-2026-012",
      tipoSolicitud: TipoSolicitud.ACTUALIZACION,
      tipoCuenta: TipoCuenta.PERMANENTE,
      nombreApellidos: "Pendiente María",
      cargoOcupa: "Coordinadora",
      departamentoArea: "RRHH",
      tipoPersonal: TipoPersonal.DIRECTIVO,
      identificadorCuentaUsuario: "pendientemaria",
      correoNacional: true,
      intranetUNE: true,
      intranetNacional: true,
      internet: true,
      mensajeriaCorporativa: true,
      pcNombre: "PC-PMARIA-001",
      pcInventario: "INV-012",
      softwareAutorizado: "Office 365, BUK HR",
      cuentaUsuario: "pendientemaria@empresa.com",
      actividadRealiza: "Coordinación de personal",
      telefonoCelular: "555-999-0000",
      solicitadoFecha: new Date("2026-06-23"),
      revisadoFecha: new Date("2026-06-25"),
    },
    // 13. Pendiente Carlos - ACTUALIZACION, PERMANENTE - Solicitado, revisado y aprobado
    {
      folio: "FOL-2026-013",
      tipoSolicitud: TipoSolicitud.ACTUALIZACION,
      tipoCuenta: TipoCuenta.PERMANENTE,
      nombreApellidos: "Pendiente Carlos",
      cargoOcupa: "Técnico",
      departamentoArea: "Sistemas",
      tipoPersonal: TipoPersonal.TECNICO,
      identificadorCuentaUsuario: "pendientecarlos",
      correoNacional: true,
      intranetUNE: true,
      internet: true,
      mensajeriaCorporativa: true,
      accesoNubeLectura: true,
      pcNombre: "PC-PCARLOS-001",
      pcInventario: "INV-013",
      softwareAutorizado: "Linux, Bash, Python, Docker",
      cuentaUsuario: "pendientecarlos@empresa.com",
      actividadRealiza: "Administración de servidores",
      telefonoCelular: "555-000-1111",
      solicitadoFecha: new Date("2026-06-24"),
      revisadoFecha: new Date("2026-06-26"),
      aprobadoFecha: new Date("2026-06-27"),
    },
  ];

  await prisma.accountRequest.createMany({ data });
  console.log(`Creadas ${data.length} solicitudes de prueba`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
