import "dotenv/config";
import prisma from "@/lib/prisma";
import { Prisma } from "@/generated/prisma/client";
import {
  TipoSolicitud,
  TipoCuenta,
  TipoPersonal,
  AccountRequestStage,
} from "@/generated/prisma/enums";

// Firmantes ficticios coherentes por etapa del flujo.
const SIGNERS: Record<
  AccountRequestStage,
  { nombre: string; cargo: string }
> = {
  [AccountRequestStage.requested]: {
    nombre: "José Ramírez",
    cargo: "Director de Informática",
  },
  [AccountRequestStage.revised]: {
    nombre: "María Gómez",
    cargo: "Especialista de Seguridad Informática",
  },
  [AccountRequestStage.approved]: {
    nombre: "Ana Rodríguez",
    cargo: "Directora General",
  },
  [AccountRequestStage.executed]: {
    nombre: "Carlos Díaz",
    cargo: "Especialista de Sistemas",
  },
};

// Convierte un mapa etapa -> fecha en el input anidado de `signatures.create`
// con el nombre y cargo del firmante ficticio de cada etapa.
const sign = (dates: Partial<Record<AccountRequestStage, Date>>) => {
  const create = (Object.entries(dates) as [AccountRequestStage, Date][]).map(
    ([stage, fecha]) => ({ stage, ...SIGNERS[stage], fecha }),
  );
  return { create };
};

async function main() {
  await prisma.accountRequest.deleteMany();

  const data: Prisma.AccountRequestCreateInput[] = [
    // 1. Juan Pérez - ALTA, PERMANENTE, TECNICO - Acceso completo
    {
      folio: "FOL-2026-001",
      tipoSolicitud: TipoSolicitud.ALTA,
      tipoCuenta: TipoCuenta.PERMANENTE,
      nombreApellidos: "Juan Pérez",
      telefonoExtension: "Ext. 101",
      cargoOcupa: "Analista",
      departamentoArea: "TI",
      tipoPersonal: TipoPersonal.TECNICO,
      identificadorCuentaUsuario: "jperez",
      correoNacional: true,
      correoInternacional: true,
      correoInternet: true,
      intranetUNE: true,
      intranetNacional: true,
      internet: true,
      mensajeriaCorporativa: true,
      facebook: true,
      twitter: true,
      youtube: true,
      whatsapp: true,
      telegram: true,
      adminRed: true,
      adminLocal: true,
      usuarioAvanzado: true,
      accesoNubeLectura: true,
      accesoNubeModificar: true,
      accesoNubeBorrar: true,
      accesoNubeControlTotal: true,
      horarioExtralaboral: true,
      extraDesde: "18:00",
      extraHasta: "22:00",
      sabadoDesde: "08:00",
      sabadoHasta: "14:00",
      apnCorreoNacional: true,
      apnInternet: true,
      telefonoCelular: "555-123-4567",
      pcNombre: "PC-JPEREZ-001",
      pcInventario: "INV-001",
      softwareAutorizado: "Visual Studio Code, Docker, PostgreSQL, Node.js",
      signatures: sign({
        requested: new Date("2026-06-01"),
        revised: new Date("2026-06-03"),
        approved: new Date("2026-06-05"),
        executed: new Date("2026-06-06"),
      }),
    },
    // 2. María López - ALTA, PERMANENTE, DIRECTIVO - Solo correo e intranet básicos
    {
      folio: "FOL-2026-002",
      tipoSolicitud: TipoSolicitud.ALTA,
      tipoCuenta: TipoCuenta.PERMANENTE,
      nombreApellidos: "María López",
      cargoOcupa: "Directora",
      departamentoArea: "RRHH",
      tipoPersonal: TipoPersonal.DIRECTIVO,
      identificadorCuentaUsuario: "mlopez",
      correoNacional: true,
      intranetUNE: true,
      intranetNacional: true,
      internet: true,
      mensajeriaCorporativa: true,
      pcNombre: "PC-MLOPEZ-001",
      pcInventario: "INV-002",
      softwareAutorizado: "Office 365, Nómina SQL",
      telefonoCelular: "555-111-2222",
      signatures: sign({
        requested: new Date("2026-06-02"),
        revised: new Date("2026-06-04"),
        approved: new Date("2026-06-06"),
        executed: new Date("2026-06-07"),
      }),
    },
    // 3. Roberto Sánchez - ALTA, PERMANENTE, OTRO
    {
      folio: "FOL-2026-003",
      tipoSolicitud: TipoSolicitud.ALTA,
      tipoCuenta: TipoCuenta.PERMANENTE,
      nombreApellidos: "Roberto Sánchez",
      cargoOcupa: "Coordinador",
      departamentoArea: "Operaciones",
      tipoPersonal: TipoPersonal.OTRO,
      identificadorCuentaUsuario: "rsanchez",
      correoNacional: true,
      intranetUNE: true,
      internet: true,
      mensajeriaCorporativa: true,
      pcNombre: "PC-RSANCHEZ-001",
      pcInventario: "INV-003",
      softwareAutorizado: "Office 365, SAP",
      telefonoCelular: "555-222-3333",
      signatures: sign({
        requested: new Date("2026-06-03"),
        revised: new Date("2026-06-05"),
        approved: new Date("2026-06-07"),
        executed: new Date("2026-06-08"),
      }),
    },
    // 4. Laura García - ALTA, TEMPORAL, ESPECIALISTA_PRINCIPAL - Con expiración
    {
      folio: "FOL-2026-004",
      tipoSolicitud: TipoSolicitud.ALTA,
      tipoCuenta: TipoCuenta.TEMPORAL,
      nombreApellidos: "Laura García",
      cargoOcupa: "Especialista",
      departamentoArea: "Sistemas",
      tipoPersonal: TipoPersonal.ESPECIALISTA_PRINCIPAL,
      identificadorCuentaUsuario: "lgarcia",
      correoNacional: true,
      correoInternacional: true,
      correoInternet: true,
      intranetUNE: true,
      intranetNacional: true,
      internet: true,
      mensajeriaCorporativa: true,
      usuarioAvanzado: true,
      accesoNubeLectura: true,
      accesoNubeModificar: true,
      fechaExpiracion: new Date("2026-12-31"),
      pcNombre: "PC-LGARCIA-001",
      pcInventario: "INV-004",
      softwareAutorizado: "VMware, Ansible, Terraform",
      telefonoCelular: "555-333-4444",
      signatures: sign({
        requested: new Date("2026-06-05"),
        revised: new Date("2026-06-07"),
        approved: new Date("2026-06-09"),
        executed: new Date("2026-06-10"),
      }),
    },
    // 5. Diego Fernández - ALTA, TEMPORAL, TECNICO - Horario extralaboral
    {
      folio: "FOL-2026-005",
      tipoSolicitud: TipoSolicitud.ALTA,
      tipoCuenta: TipoCuenta.TEMPORAL,
      nombreApellidos: "Diego Fernández",
      cargoOcupa: "Técnico",
      departamentoArea: "Redes",
      tipoPersonal: TipoPersonal.TECNICO,
      identificadorCuentaUsuario: "dfernandez",
      correoNacional: true,
      intranetUNE: true,
      internet: true,
      mensajeriaCorporativa: true,
      accesoNubeLectura: true,
      fechaExpiracion: new Date("2026-09-30"),
      horarioExtralaboral: true,
      extraDesde: "20:00",
      extraHasta: "00:00",
      domingoDesde: "10:00",
      domingoHasta: "14:00",
      apnCorreoNacional: true,
      apnInternet: true,
      telefonoCelular: "555-987-6543",
      pcNombre: "PC-DFERNANDEZ-001",
      pcInventario: "INV-005",
      softwareAutorizado: "Wireshark, Putty, Cisco CLI",
      signatures: sign({
        requested: new Date("2026-06-06"),
        revised: new Date("2026-06-08"),
        approved: new Date("2026-06-10"),
        executed: new Date("2026-06-11"),
      }),
    },
    // 6. Ana Martínez - ACTUALIZACION, PERMANENTE, DIRECTIVO - Se le agregan permisos
    {
      folio: "FOL-2026-006",
      tipoSolicitud: TipoSolicitud.ACTUALIZACION,
      tipoCuenta: TipoCuenta.PERMANENTE,
      nombreApellidos: "Ana Martínez",
      cargoOcupa: "Jefa",
      departamentoArea: "Finanzas",
      tipoPersonal: TipoPersonal.DIRECTIVO,
      identificadorCuentaUsuario: "amartinez",
      correoNacional: true,
      correoInternacional: true,
      intranetUNE: true,
      intranetNacional: true,
      internet: true,
      mensajeriaCorporativa: true,
      pcNombre: "PC-AMARTINEZ-001",
      pcInventario: "INV-006",
      pcAdicionalNombre: "PC-AMARTINEZ-MOVIL",
      pcAdicionalInventario: "INV-006B",
      softwareAutorizado: "Office 365, SAP FI, Power BI",
      telefonoCelular: "555-444-5555",
      signatures: sign({
        requested: new Date("2026-06-08"),
        revised: new Date("2026-06-10"),
        approved: new Date("2026-06-12"),
        executed: new Date("2026-06-13"),
      }),
    },
    // 7. Carlos Ruiz - ACTUALIZACION, TEMPORAL, TECNICO - Cambio de área
    {
      folio: "FOL-2026-007",
      tipoSolicitud: TipoSolicitud.ACTUALIZACION,
      tipoCuenta: TipoCuenta.TEMPORAL,
      nombreApellidos: "Carlos Ruiz",
      cargoOcupa: "Analista",
      departamentoArea: "TI",
      tipoPersonal: TipoPersonal.TECNICO,
      identificadorCuentaUsuario: "cruiz",
      correoNacional: true,
      correoInternacional: true,
      intranetUNE: true,
      internet: true,
      mensajeriaCorporativa: true,
      usuarioAvanzado: true,
      accesoNubeLectura: true,
      accesoNubeModificar: true,
      fechaExpiracion: new Date("2026-08-15"),
      pcNombre: "PC-CRUIZ-001",
      pcInventario: "INV-007",
      softwareAutorizado: "Postman, Git, VS Code, DBeaver",
      signatures: sign({
        requested: new Date("2026-06-10"),
        revised: new Date("2026-06-12"),
        approved: new Date("2026-06-14"),
        executed: new Date("2026-06-15"),
      }),
    },
    // 8. Sofía Torres - ACTUALIZACION, PERMANENTE, ESPECIALISTA_PRINCIPAL
    {
      folio: "FOL-2026-008",
      tipoSolicitud: TipoSolicitud.ACTUALIZACION,
      tipoCuenta: TipoCuenta.PERMANENTE,
      nombreApellidos: "Sofía Torres",
      cargoOcupa: "Especialista",
      departamentoArea: "Legal",
      tipoPersonal: TipoPersonal.ESPECIALISTA_PRINCIPAL,
      identificadorCuentaUsuario: "storres",
      correoNacional: true,
      correoInternacional: true,
      intranetUNE: true,
      intranetNacional: true,
      internet: true,
      mensajeriaCorporativa: true,
      youtube: true,
      pcNombre: "PC-STORRES-001",
      pcInventario: "INV-008",
      softwareAutorizado: "Office 365, LexisNexis, Dropbox",
      telefonoCelular: "555-555-6666",
      signatures: sign({
        requested: new Date("2026-06-12"),
        revised: new Date("2026-06-14"),
        approved: new Date("2026-06-16"),
        executed: new Date("2026-06-17"),
      }),
    },
    // 9. Pedro Ramírez - ACTUALIZACION, TEMPORAL, TECNICO - Cambio de horario
    {
      folio: "FOL-2026-009",
      tipoSolicitud: TipoSolicitud.ACTUALIZACION,
      tipoCuenta: TipoCuenta.TEMPORAL,
      nombreApellidos: "Pedro Ramírez",
      cargoOcupa: "Técnico",
      departamentoArea: "Mantenimiento",
      tipoPersonal: TipoPersonal.TECNICO,
      identificadorCuentaUsuario: "pramirez",
      correoNacional: true,
      intranetUNE: true,
      mensajeriaCorporativa: true,
      fechaExpiracion: new Date("2026-07-01"),
      horarioExtralaboral: true,
      extraDesde: "18:00",
      extraHasta: "22:00",
      sabadoDesde: "06:00",
      sabadoHasta: "14:00",
      domingoDesde: "06:00",
      domingoHasta: "12:00",
      pcNombre: "PC-PRAMIREZ-001",
      pcInventario: "INV-009",
      softwareAutorizado: "Autocad, SolidWorks",
      telefonoCelular: "555-666-7777",
      signatures: sign({
        requested: new Date("2026-06-14"),
        revised: new Date("2026-06-16"),
        approved: new Date("2026-06-18"),
        executed: new Date("2026-06-19"),
      }),
    },
    // 10. Elena Díaz - Baja
    {
      folio: "FOL-2026-010",
      tipoSolicitud: TipoSolicitud.ALTA,
      tipoCuenta: TipoCuenta.PERMANENTE,
      nombreApellidos: "Elena Díaz",
      cargoOcupa: "Directora",
      departamentoArea: "Comercial",
      tipoPersonal: TipoPersonal.DIRECTIVO,
      identificadorCuentaUsuario: "ediaz",
      correoNacional: true,
      correoInternacional: true,
      intranetUNE: true,
      intranetNacional: true,
      internet: true,
      mensajeriaCorporativa: true,
      pcNombre: "PC-EDIAZ-001",
      pcInventario: "INV-010",
      softwareAutorizado: "Office 365, Salesforce, Tableau",
      telefonoCelular: "555-777-8888",
      motivosBaja: "Cambio a otra institución",
      fechaBaja: new Date("2026-06-20"),
      signatures: sign({
        requested: new Date("2026-01-10"),
        revised: new Date("2026-01-12"),
        approved: new Date("2026-01-14"),
        executed: new Date("2026-01-15"),
      }),
    },
    // 11. Pendiente Juan - ALTA, TEMPORAL - Solo solicitado
    {
      folio: "FOL-2026-011",
      tipoSolicitud: TipoSolicitud.ALTA,
      tipoCuenta: TipoCuenta.TEMPORAL,
      nombreApellidos: "Pendiente Juan",
      cargoOcupa: "Analista",
      departamentoArea: "TI",
      tipoPersonal: TipoPersonal.TECNICO,
      identificadorCuentaUsuario: "pendientejuan",
      correoNacional: true,
      intranetUNE: true,
      internet: true,
      mensajeriaCorporativa: true,
      fechaExpiracion: new Date("2026-11-30"),
      pcNombre: "PC-PJUAN-001",
      pcInventario: "INV-011",
      softwareAutorizado: "VS Code, Node.js, MySQL",
      telefonoCelular: "555-888-9999",
      signatures: sign({
        requested: new Date("2026-06-22"),
      }),
    },
    // 12. Pendiente María - ACTUALIZACION, PERMANENTE - Solicitado y revisado
    {
      folio: "FOL-2026-012",
      tipoSolicitud: TipoSolicitud.ACTUALIZACION,
      tipoCuenta: TipoCuenta.PERMANENTE,
      nombreApellidos: "Pendiente María",
      cargoOcupa: "Coordinadora",
      departamentoArea: "RRHH",
      tipoPersonal: TipoPersonal.DIRECTIVO,
      identificadorCuentaUsuario: "pendientemaria",
      correoNacional: true,
      intranetUNE: true,
      intranetNacional: true,
      internet: true,
      mensajeriaCorporativa: true,
      pcNombre: "PC-PMARIA-001",
      pcInventario: "INV-012",
      softwareAutorizado: "Office 365, BUK HR",
      telefonoCelular: "555-999-0000",
      signatures: sign({
        requested: new Date("2026-06-23"),
        revised: new Date("2026-06-25"),
      }),
    },
    // 13. Pendiente Carlos - ACTUALIZACION, PERMANENTE - Solicitado, revisado y aprobado
    {
      folio: "FOL-2026-013",
      tipoSolicitud: TipoSolicitud.ACTUALIZACION,
      tipoCuenta: TipoCuenta.PERMANENTE,
      nombreApellidos: "Pendiente Carlos",
      cargoOcupa: "Técnico",
      departamentoArea: "Sistemas",
      tipoPersonal: TipoPersonal.TECNICO,
      identificadorCuentaUsuario: "pendientecarlos",
      correoNacional: true,
      intranetUNE: true,
      internet: true,
      mensajeriaCorporativa: true,
      accesoNubeLectura: true,
      pcNombre: "PC-PCARLOS-001",
      pcInventario: "INV-013",
      softwareAutorizado: "Linux, Bash, Python, Docker",
      telefonoCelular: "555-000-1111",
      signatures: sign({
        requested: new Date("2026-06-24"),
        revised: new Date("2026-06-26"),
        approved: new Date("2026-06-27"),
      }),
    },
  ];

  for (const record of data) {
    await prisma.accountRequest.create({ data: record });
  }
  console.log(`Creadas ${data.length} solicitudes de prueba`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());