-- CreateEnum
CREATE TYPE "TipoSolicitud" AS ENUM ('ALTA', 'ACTUALIZACION', 'MODIFICACION');

-- CreateEnum
CREATE TYPE "TipoPersonal" AS ENUM ('DIRECTIVO', 'ESPECIALISTA_PRINCIPAL', 'TECNICO', 'OTRO');

-- CreateEnum
CREATE TYPE "TipoCuenta" AS ENUM ('PERMANENTE', 'TEMPORAL');

-- CreateTable
CREATE TABLE "AccountRequest" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "folio" TEXT,
    "tipoSolicitud" "TipoSolicitud" NOT NULL,
    "nombreApellidos" TEXT NOT NULL,
    "cargoOcupa" TEXT NOT NULL,
    "departamentoArea" TEXT NOT NULL,
    "tipoPersonal" "TipoPersonal" NOT NULL,
    "cuenta" TEXT,
    "correoLocal" BOOLEAN NOT NULL DEFAULT false,
    "correoNacional" BOOLEAN NOT NULL DEFAULT false,
    "correoInternacional" BOOLEAN NOT NULL DEFAULT false,
    "correoInternet" BOOLEAN NOT NULL DEFAULT false,
    "correoInternetFechaTemp" TIMESTAMP(3),
    "intranetUNE" BOOLEAN NOT NULL DEFAULT false,
    "intranetNacional" BOOLEAN NOT NULL DEFAULT false,
    "internet" BOOLEAN NOT NULL DEFAULT false,
    "internetFechaTemp" TIMESTAMP(3),
    "mensajeriaCorporativa" BOOLEAN NOT NULL DEFAULT false,
    "chatInternet" BOOLEAN NOT NULL DEFAULT false,
    "chatInternetFechaTemp" TIMESTAMP(3),
    "facebook" BOOLEAN NOT NULL DEFAULT false,
    "twitter" BOOLEAN NOT NULL DEFAULT false,
    "youtube" BOOLEAN NOT NULL DEFAULT false,
    "otrasRedes" TEXT,
    "adminRed" BOOLEAN NOT NULL DEFAULT false,
    "adminLocal" BOOLEAN NOT NULL DEFAULT false,
    "usuarioAvanzado" BOOLEAN NOT NULL DEFAULT false,
    "ftpUneLectura" BOOLEAN NOT NULL DEFAULT false,
    "ftpUneModificar" BOOLEAN NOT NULL DEFAULT false,
    "ftpUneBorrar" BOOLEAN NOT NULL DEFAULT false,
    "ftpEntidadLectura" BOOLEAN NOT NULL DEFAULT false,
    "ftpEntidadModificar" BOOLEAN NOT NULL DEFAULT false,
    "ftpEntidadBorrar" BOOLEAN NOT NULL DEFAULT false,
    "tipoCuenta" "TipoCuenta" NOT NULL,
    "fechaExpiracion" TIMESTAMP(3),
    "horarioExtralaboral" BOOLEAN NOT NULL DEFAULT false,
    "extraDesde" TEXT,
    "extraHasta" TEXT,
    "sabadoDesde" TEXT,
    "sabadoHasta" TEXT,
    "domingoDesde" TEXT,
    "domingoHasta" TEXT,
    "apnCorreoNacional" BOOLEAN NOT NULL DEFAULT false,
    "apnCorreoInternacional" BOOLEAN NOT NULL DEFAULT false,
    "apnInternet" BOOLEAN NOT NULL DEFAULT false,
    "telefonoCelular" TEXT,
    "pcNombre" TEXT,
    "pcInventario" TEXT,
    "pcAdicionalNombre" TEXT,
    "pcAdicionalInventario" TEXT,
    "softwareAutorizado" TEXT,
    "cuentaUsuario" TEXT,
    "actividadRealiza" TEXT,
    "administradorSistema" BOOLEAN NOT NULL DEFAULT false,
    "solicitadoNombre" TEXT,
    "solicitadoCargo" TEXT,
    "solicitadoFecha" TIMESTAMP(3),
    "revisadoNombre" TEXT,
    "revisadoCargo" TEXT,
    "revisadoFecha" TIMESTAMP(3),
    "aprobadoNombre" TEXT,
    "aprobadoCargo" TEXT,
    "aprobadoFecha" TIMESTAMP(3),
    "ejecutadoNombre" TEXT,
    "ejecutadoCargo" TEXT,
    "ejecutadoFecha" TIMESTAMP(3),
    "bajaEntidad" BOOLEAN NOT NULL DEFAULT false,
    "motivosBaja" TEXT,
    "fechaBaja" TIMESTAMP(3),

    CONSTRAINT "AccountRequest_pkey" PRIMARY KEY ("id")
);
